# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Testing App 123"
client_id = "c484b2a6c0fe6aab173032cbd066b977"
application_url = "https://quality-tucson-commit-taxes.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://quality-tucson-commit-taxes.trycloudflare.com/auth/callback",
  "https://quality-tucson-commit-taxes.trycloudflare.com/auth/shopify/callback",
  "https://quality-tucson-commit-taxes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newbie-dkcx.myshopify.com"
